### ISSUE TITLE
Ссылка на муську в README

### ISSUE THREAD

**Issue by Bougakov** [ACE1046/LazyRolls#1]
Пожалуйста, поставьте ссылку на свою статью https://mysku.ru/blog/diy/62110.html в README.md, а то ж не найти потом... Спасибо!

**Comment by ACE1046** [comment]
Благодарю! Совсем забыл про это.
Сделано.

**Comment by T-REX-XP** [comment]
Во время тестирования, замечаю странное поведение. Шторы не работатю вместе на одном окне. То ли теряют подключение к wifi, толи в сон входят. Пробовал разносить по разным блоками питания и по разным сетям wifi. Первое время после старта вроде доступны обе админки и можно управлять, но когда на ночь оставляешь что утром только одна открывается.
