### ISSUE TITLE
Возможность отключить концевик

### ISSUE THREAD

**Issue by vapustovoyt** [ACE1046/LazyRolls#11]
Использую Вашу прошивку и 2 привода в режиме мастер-слейв для шторы 2.2м. Было бы удобно отключить на ведомом концевик.
Спасибо за труды!

**Comment by ACE1046** [comment]
Так по идее можно поставить джампер заместо концевика или выбрать в настройках "нормально разомкнут"?
Если использовать два мотора синхронно на одной шторе, то надежнее просто запараллелить моторы (направление вращения меняется перестановкой концов одной из обмоток). Потребуется 4 провода между приводами, не считая питания, но надежнее.

**Comment by vapustovoyt** [comment]
Просто штора едет после перезагрузки в верхнее положение и нужно 2 концевика. ну или тащить с одного провода. Может действительно поставлю 2 мотора на 1 драйвер. Спасибо

**Comment by vapustovoyt** [comment]
Подключил 2 двигателя, бросил только питание  по 4м кабелям на удаленный двигатель и теперь не актуально.
