### ISSUE TITLE
OTA обновление

### ISSUE THREAD

**Issue by Pech0rin** [ACE1046/LazyRolls#13]
При попытке обновить прошивку по воздуху требует логин и пароль.

**Comment by ACE1046** [comment]
Логин и пароль admin admin Если нужно их изменить, то меняются в исходнике, требуется перекомпиляция.
Начиная с версии 11 или 12, точно не помню, подсказка написана прямо на странице прошивки.

**Comment by Pech0rin** [comment]
Благодарю
